// components/MarketingAbout/MarketingAbout.tsx
import styles from "./MarketingAbout.module.css";

export default function MarketingAbout() {
	return (
		<section id="about" className={styles['c-mkt-about']}>
			<div>About Focus</div>
			<h2>We&apos;re bringing the best parts of OKRs and simple task tracking.</h2>

			<p>Focus is still in early stage of development but if you are looking for a way to track your day-to-day work,
          Focus can help you now and we will be working to add quarterly tracking soon.</p>
		</section>);
}

// src/pages/index/components/MarketingAbout.svelte
<section id="about" class="c-mkt-about">
  <div>About Focus</div>
  <h2>We&apos;re bringing the best parts of OKRs and simple task tracking.</h2>

  <p>Focus is still in early stage of development but if you are looking for a way to track your day-to-day work,
      Focus can help you now and we will be working to add quarterly tracking soon.</p>
</section>

<style>
.c-mkt-about {
	width: 100%;
	max-width: var(--width);
	margin: var(--xl-padding) auto;
}

.c-mkt-about > div {
	text-align: center;
	color: var(--orange);
	font-family: var(--title-family);
	font-weight: 700;
}

.c-mkt-about > h2 {
	text-align: center;
	font-weight: 600;
}

.c-mkt-about > p {
	max-width: 80%;
	margin-left: auto;
	margin-right: auto;
	text-align: center;
}
</style>
