// src/lib/components/SignInButton.svelte
<script lang="ts">
	import { auth } from '$lib/logic/auth/auth';
	import Button, { Modifier } from '$lib/components/Button.svelte';

	export let modifier: Modifier | undefined = undefined;
</script>

{#if auth.user && auth.user.email}
	<Button on:click={() => auth.signOut()} {modifier}>Sign Out</Button>
{:else}
	<Button on:click={() => auth.signIn()} {modifier}><slot>Sign In</slot></Button>
{/if}

// src/components/SignInButton/SignInButton.tsx
import { GoogleAuthProvider } from "firebase/auth";
import { useAuth } from '../../contexts/Auth';

export function SignInButton({classModifier, signInText = 'Sign In', redirect = "/home"}: SignInButtonProps) {
	const classList = [];
	if (classModifier) {
		classList.push(`button--${classModifier}`);
	}

	const {signIn, signOut, user} = useAuth();
	if (user && user.email) {
		return (
			<button className={classList.join(' ')} onClick={() => signOut()}>Sign Out</button>
		);
	}

	return (
		<button className={classList.join(' ')} onClick={() => signIn(new GoogleAuthProvider(), redirect)}>{signInText}</button>
	);
}

interface SignInButtonProps {
  classModifier?: string;
  signInText?: string;
  redirect?: string;
}
