// src/pages/Cookies/Cookies.tsx
import { LegalPage } from "@/components/LegalPage/LegalPage";

export function Cookies() {
	return (
		<LegalPage>
			<h1>Cookies</h1>
			<p>Last updated: Mar 12, 2023</p>

			<h2>Required Cookies</h2>

			<p>
				We strive to only store cookies that are necessary to make This tool
				function correctly.
			</p>

			<p>
				At the time of writing the only cookies we use are the cookies created
				by <a href="https://firebase.google.com">Firebase/Google</a>, which are
				used for authentication.
			</p>

			<h2>Analytics and Tracking</h2>

			<p>
				Beampipe is used to get analytics on Focuses usage. We have selected
				Beampipe due to it&apos;s privacy focus.
			</p>

			<p>
				You can view the data we track{" "}
				<a
					href="https://app.beampipe.io/domain/focus.gaunt.dev"
					target="_blank"
				>
					here
				</a>
				.
			</p>
		</LegalPage>
	);
}

// src/routes/cookies/+page.svelte
<script lang="ts">
	import '$lib/styles/reset.css';
	import LegalPage from '$lib/layouts/LegalPage.svelte';
</script>

<LegalPage>
	<h1>Cookies</h1>
	<p>Last updated: Mar 12, 2023</p>

	<h2>Required Cookies</h2>

	<p>We strive to only store cookies that are necessary to make This tool function correctly.</p>

	<p>
		At the time of writing the only cookies we use are the cookies created by <a
			href="https://firebase.google.com">Firebase/Google</a
		>, which are used for authentication.
	</p>

	<h2>Analytics and Tracking</h2>

	<p>
		Beampipe is used to get analytics on Focuses usage. We have selected Beampipe due to it&apos;s
		privacy focus.
	</p>

	<p>
		You can view the data we track <a
			href="https://app.beampipe.io/domain/focus.gaunt.dev"
			target="_blank">here</a
		>.
	</p>
</LegalPage>
