// components/SignInButton/SignInButton.tsx
import { useAuth } from '../../contexts/Auth';
import { GoogleAuthProvider } from "firebase/auth";

export default function SignInButton({classModifier, signInText = 'Sign In', redirect = "/home"}: SignInButtonProps) {
	const classList = [];
	if (classModifier) {
		classList.push(`button--${classModifier}`);
	}

	const {signIn, signOut, user} = useAuth();
	if (user && user.email) {
		return (
			<button className={classList.join(' ')} onClick={() => signOut()}>Sign Out</button>
		);
	}

	return (
		<button className={classList.join(' ')} onClick={() => signIn(new GoogleAuthProvider(), redirect)}>{signInText}</button>
	);
}

interface SignInButtonProps {
  classModifier?: string;
  signInText?: string;
  redirect?: string;
}

// src/common/components/SignInButton.svelte
<script lang="ts">
  import { auth, userStore } from "../auth/auth";
  import Button, { Modifier } from "./Button.svelte";

  export let modifier: Modifier | undefined = undefined;
</script>

{#if $userStore && $userStore.email}
  <Button on:click={() => auth.signOut()} {modifier}>Sign Out</Button>
{:else}
  <Button on:click={() => auth.signIn()} {modifier}><slot>Sign In</slot></Button>
{/if}
