// src/pages/index/components/MarketingNav.svelte
<script lang="ts">
  import SignInButton from '../../../common/components/SignInButton.svelte';
  import Button, { Modifier } from '../../../common/components/Button.svelte';
  import { userStore, auth } from '../../../common/auth/auth';
</script>

<section class="c-mkt-nav">
  <a href="/"><img width="48" height="48" src="/logo/mini-logo.svg" alt="Small Focus Logo" /></a>

  <div class="c-mkt-nav__menu">
    <SignInButton modifier={$userStore === null ? undefined : Modifier.Subtle} />
    {#if $userStore && $userStore.email}
      <a href="/home"><Button>Tasks</Button></a>
    {/if}
  </div>
</section>

<style>
.c-mkt-nav {
	display: flex;
	flex-direction: row;
	justify-content: space-between;
	align-items: center;
	width: 100%;
	max-width: var(--width);
	margin: var(--m-padding) auto;
}

.c-mkt-nav__menu {
	display: flex;
	flex-direction: row;
	align-items: center;
	gap: var(--m-padding);
}
</style>

// frontend/app/components/marketing/MarketingNav/MarketingNav.tsx
import { useAuth } from '~/contexts/Auth';
import styles from "./MarketingNav.module.css";
import { SignInButton } from '~/components/SignInButton/SignInButton';
import { Link } from "@remix-run/react";

export function MarketingNav() {
	const {user} = useAuth();
	let taskBtn;
	let modifer;
	if (user && user.email) {
		taskBtn = (
			<Link to="/home"><button>Tasks</button></Link>
		);
		modifer = 'subtle';
	}

	return (
		<section className={styles['c-mkt-nav']}>
			<Link to="/"><img width="48" height="48" src="/logo/mini-logo.svg" alt="Small Focus Logo" /></Link>

			<div className={styles['c-mkt-nav__menu']}>
				<SignInButton classModifier={modifer} />
				{taskBtn}
			</div>
		</section>);
}
